from hbd import Draw, Line, Network, Styler

config = Network(
    title='Topographical Map of Railways in Sri Lanka',
    subtitle="Sri Lanka",
    footer_text='Not to scale.',
    line_idx={
        'Main': Line(
            color="red",
            station_list=[
                "Colombo Fort",
                "Maradana",
                "Dematagoda",
                "Kelaniya",
                "Wanawasala",
                "Hunupitiya",
                "Ederamulla",
                "Horape",
                "Ragama Junction",
                "Walpola",
                "Batuwaththa",
                "Bulugahagoda",
                "Ganemulla",
                "Yagoda",
                "Gampaha",
                "Daraluwa",
                "Bemmulla",
                "Magalegoda",
                "Heendeniya Pattiyagoda",
                "Veyangoda",
                "Wadurawa",
                "Keenawala",
                "Pallewela",
                "Ganegoda",
                "Wijaya Rajadahana",
                "Meerigama",
                "Wilwatta",
                "Botale",
                "Ambepussa",
                "Yaththalgoda",
                "Bujjomuwa",
                "Alawwa",
                "Walakumbura",
                "Polgahawela Junction",
                "Panaliya",
                "Tismalpola",
                "Korossa",
                "Yatagama",
                "Rambukkana",
                "Kadigamuwa",
                "Yatiweldeniya",
                "Gangoda",
                "Ihala Kotte",
                "Bambaragala",
                "Makehelwala",
                "Balana",
                "Weralugolla",
                "Kadugannawa",
                "Kotabogolla",
                "Urapola",
                "Pilimatalawa",
                "Barammane",
                "Kiribathkumbura",
                "Peradeniya Junction",
                "Koshinna",
                "Gelioya",
                "Polgahaanga",
                "Weligalla",
                "Botalapitiya",
                "Gangathilaka",
                "Kahatapitiya",
                "Gampola",
                "Wallahagoda",
                "Tembiligala",
                "Warakapitiya",
                "Ulapane",
                "Pallegama",
                "Warakawa",
                "Nawalapitiya",
                "Selam",
                "Hieghtenford",
                "Inguruoya",
                "Penrose",
                "Galboda",
                "Dekinda",
                "Wewelthalawa",
                "Watawala",
                "Ihala Watawala",
                "Rozella",
                "Hatton",
                "Galkandawatta",
                "Kotagala",
                "St. Clair",
                "Thalawakelle",
                "Watagoda",
                "Great Western",
                "Radella",
                "Nanu Oya",
                "Perakumpura",
                "Ambewela",
                "Pattipola",
                "Ohiya",
                "Idalgashinna",
                "Glenanore",
                "Haputale",
                "Diyatalawa",
                "Bandarawela",
                "Kinigama",
                "Heeloya",
                "Kitalella",
                "Ella",
                "Demodara",
                "Uduwara",
                "Hali-Ela",
                "Badulla",
            ],
            path="20NE 20E 20SE 20E 20NE 4N",
        ),
        'Northern': Line(
            color="cyan",
            station_list=[
                "Polgahawela Junction",
                "Girambe",
                "Thalawattegedara",
                "Potuhara",
                "Nailiya",
                "Kurunegala",
                "Muttettugala",
                "Wellawa",
                "Pinnagolla",
                "Ganewatta",
                "Hiriyala",
                "Nagollagama",
                "Thimbiriyagedara",
                "Maho Junction",
                "Randenigama",
                "Ambanpola",
                "Galgamuwa",
                "Senarathgama",
                "Thambuttegama",
                "Talawa",
                "Shrawasthipura",
                "Anuradhapura New Town",
                "Anuradhapura",
                "Mihintale Junction",
                "Parasangahawewa",
                "Medagama",
                "Siyambalagahawewa",
                "Medawachchiya Junction",
                "Poonewa",
                "Eratperiakulam",
                "Vavuniya",
                "Thandikulam",
                "Omanthai",
                "Puliyankulam",
                "Mankulam",
                "Murukandi",
                "Ariviya Nagar",
                "Kilinochchi",
                "Paranthan",
                "Elephantpass",
                "Pallai",
                "Eluthumadduval",
                "Mirusuvil",
                "Kodikamamam",
                "Meesalai",
                "Sankathanai",
                "Chavakachcheri",
                "Thachanthoppu",
                "Navatkuly",
                "Punkankulam",
                "Jaffna",
                "Kokuvil",
                "Kondavil",
                "Inuvil",
                "Chunnakam",
                "Malakkam",
                "Tellippalai",
                "Maviddapuram",
                "Kankesanthurai",
            ],
            path="20N 20N 10NW 8N",
        ),
        'Coastal': Line(
            color="cyan",
            station_list=[
                "Colombo Fort",
                "Secretariant Halt",
                "Kompanna Veediya",
                "Kollupitiya",
                "Bambalapitiya",
                "Wellawatte",
                "Dehiwela",
                "Mount Lavinia",
                "Ratmalana",
                "Angulana",
                "Lunawa",
                "Moratuwa",
                "Koralawella",
                "Egoda Uyana",
                "Panadura",
                "Pinwatte",
                "Wadduwa",
                "Train Halt 01",
                "Kalutara North",
                "Kalutara South",
                "Katukurunda",
                "Payagala North",
                "Payagala South",
                "Maggona",
                "Beruwala",
                "Hettimulla",
                "Aluthgama",
                "Bentota",
                "Induruwa",
                "Maha Induruwa",
                "Kosgoda",
                "Piyagama",
                "Ahungalla",
                "Patagamgoda",
                "Balapitiya",
                "Andadola",
                "Kandegoda",
                "Ambalangoda",
                "Madampagama",
                "Akurala",
                "Kahawe",
                "Telwatte",
                "Sinigama",
                "Hikkaduwa",
                "Thiranagama",
                "Kumarakanda",
                "Dodanduwa",
                "Rathgama",
                "Boossa",
                "Ginthota",
                "Piyadigama",
                "Richmond Hill",
                "Galle",
                "Katugoda",
                "Unawatuna",
                "Talpe",
                "Habaraduwa",
                "Koggala",
                "Kathaluwa",
                "Ahangama",
                "Midigama",
                "Kubalgama",
                "Weligama",
                "Polwathumodara",
                "Mirissa",
                "Kamburugamuwa",
                "Walgama",
                "Matara",
                "Piladuwa",
                "Weherahena",
                "Kekandura",
                "Bambarenda",
                "Wewurukannala",
                "Nakulugamuwa",
                "Beliatta",
            ],
            path="20S 20SE 20E 10NE 4N",
        ),
        'Kelani Valley': Line(
            color="darkblue",
            station_list=[
                "Maradana",
                "Baseline Road",
                "Cotta Road",
                "Manning Town",
                "Narahenpita",
                "Kirulapone",
                "Nugegoda",
                "Pengiriwatte",
                "Udahamulla",
                "Nawinna",
                "Maharagama",
                "Pannipitiya",
                "Kottawa",
                "Malapalle",
                "Makumbura",
                "Homagama Hospital",
                "Homagama",
                "Panagoda",
                "Godagama",
                "Meegoda",
                "Watareka",
                "Liyanwala",
                "Padukka",
                "Arukwathupura",
                "Angampitiya",
                "Uggalla",
                "Pinnawala",
                "Gammana",
                "Morakale",
                "Waga",
                "Kadugoda",
                "Arapanagama",
                "Kosgama",
                "Aluthambalama",
                "Miriswatte",
                "Hingurala",
                "Puwakpitiya",
                "Puwakpitiya Town",
                "Kiriwadala",
                "Avissawella",
            ],
            path="10SE 20E 5NE 4N",
        ),
        'Puttalam': Line(
            color="green",
            station_list=[
                "Ragama Junction",
                "Peralanda",
                "Kandana",
                "Kapuwatta",
                "Ja-Ela",
                "Thudella",
                "Kudahakkapola",
                "Alawathupitiya",
                "Seeduwa",
                "Liyanagemulla",
                "Inventment Promotion Zone",
                "Colombo Airport Katunayake",
                "Katunayaka",
                "Kurana",
                "Negombo",
                "Kattuwa",
                "Kochchikade",
                "Waikkala",
                "Bolawatta",
                "Boralessa",
                "Lunuwila",
                "Thummodara",
                "Nattandiya",
                "Walahapitiya",
                "Kudawewa",
                "Nelumpokuna",
                "Madampe",
                "Kakkapalliya",
                "Sawarana",
                "Chilaw",
                "Manuwangama",
                "Bangadeniya",
                "Arachchikattuwa",
                "Anawilundawa",
                "Battuluoya",
                "Pulichchikulam",
                "Mundel",
                "Mangala Eliya",
                "Madurankuli",
                "Erukkalampiddy",
                "Palavi",
                "Thillayadi",
                "Puttalam",
                "Noor Nagar",
                "Karadipooval",
                "Periyanagavillu",
            ],
            path="9NW 11N 20N 5N",
        ),
        'Matale': Line(
            color="purple",
            station_list=[
                "Peradeniya Junction",
                "Sarasavi Uyana",
                "Rajawatte",
                "Randles Hill",
                "Suduhumpola",
                "Kandy",
                "Asgirya",
                "Mahiyawa",
                "Katugastota Road",
                "Mavilmada",
                "Katugastota",
                "Pallethalawinna",
                "Udathalawinna",
                "Meegammana",
                "Yatirawana",
                "Wattegama",
                "Yatawara",
                "Pathanpaha",
                "Marukona",
                "Udaththawala",
                "Ukuwela",
                "Tawalankoya",
                "Elwala",
                "Kohobiliwala",
                "Matale",
            ],
            path="10NE 10N 4N",
        ),
        'Mihintale': Line(
            color="maroon",
            station_list=[
                "Mihintale Junction",
                "Samagipura",
                "Ashokapura",
                "Mihintale",
            ],
            path="3E",
        ),
        'Mannar': Line(
            color="blue",
            station_list=[
                "Medawachchiya Junction",
                "Neriyakulam",
                "Cheddikulam",
                "Madhu Road",
                "Murunkan",
                "Mathotam",
                "Thirukketiswaram",
                "Mannar",
                "Thoddaveli",
                "Pesalai",
                "Talaimannar",
                "Talaimannar Pier",
            ],
            path="10NW 1W",
        ),
        'Batticaloa': Line(
            color="darkgreen",
            station_list=[
                "Maho Junction",
                "Yapahuwa",
                "Konwewa",
                "Ranamukgama",
                "Moragollagama",
                "Siyambalagamuwa",
                "Nagama",
                "Awukana",
                "Kalawewa",
                "Ihalagama",
                "Kekirawa",
                "Horiwila",
                "Palugaswewa",
                "Habarana",
                "Hatares Kotuwa",
                "Gal Oya Junction",
                "Minneriya",
                "Hingurakgoda",
                "Hathamuna",
                "Jayanthipura",
                "Laksha Uyana",
                "Parakum Uyana",
                "Polonnaruwa",
                "Gallella",
                "Manampitiya",
                "Kolakanaweli",
                "Sevanapitiya",
                "Welikanda",
                "Aselapura",
                "Rideethenna",
                "Punanai",
                "Kadathasi Nagaraya",
                "Valaichchenai",
                "Kalkudah",
                "Sittankudi",
                "Devapuram",
                "Vandaramoolai",
                "Eravur",
                "Batticaloa",
            ],
            path="10NE 5E 10SE 13E",
        ),
        'Trincomalee': Line(
            color="silver",
            station_list=[
                "Gal Oya Junction",
                "Aluth oya",
                "Agbopura",
                "Kanthalai",
                "Ganthalawa",
                "Mullipothanai",
                "Thampalakamam",
                "China Bay",
                "Trincomalee",
            ],
            path="5NE 3N",
        ),
    },
)

styler = Styler(DIM=6000)

Draw(config, styler).draw('images/lk_rail.png')
